import React from "react";
import NavLinks from './Navlinks'
import MenuList from '../Reusable-components/MenuList'

const MechanicalDeptNewPublications = () => {
   return(
    <div className="tl-event-details-container pt-100 pb-100" >
        <div className="container-fluid">
        <h2 className="tl-9-section-title py-4 rounded-tl-[40px] rounded-br-[40px] w-fit px-8 bg-[#4f70b6] font-bold text-white mx-auto mb-50">Publications</h2>
            <div className="row tl-event-details-row g-0">
            <MenuList dept="" subMenu={NavLinks} />
          <div
            data-spy="scroll"
            className="scrollspy-example z-depth-1 p-3 mb-4 col-lg-9 col-md-6 col-sm-12 dept-content"
            data-target="#menu-navbar"
            data-offset="0"
          >
            <div className="row">
                <div className="col-lg-12">
               
                    <div className="tl-event-details-left">
                        <h3 className="tl-event-details-area-title text-[#4f70b6]">Research & Publications</h3>
                        <div className="tl-event-details-key-content tl-event-details-area">
                                <ul className="tl-event-details-key-content-list phd-container">
                                   <li>Dr. V. A. Raikar, " Application of Quantitative Fishbone Diagram for Investigation of Erosion Defect in CI Casting Produced by Sand Casting", International Journal of Engineering Trends and Technology, Volume 67 Issue 1, ISSN 2231-5381, Feb-19</li>
                                   <li>Dr. V. V. Kulkarni, "Intelligent Algorithmic Multiobjective Optimization for Renewable Energy System Generation & Integration Problems: A Review", International Journal of Renewable Energy Research, Vol.9, No.1 March 2019, Page 271-280, 2.88, Mar-19, Sopus</li>
                                   <li>Dr. V. V. Kulkarni, "Thermal Energy Demand Fulfillment of Kolhapur through modelling and optimization of integrated renewable energy system" ELSEVIER Renewable energy focus,Vol-29, Number-00,Page No.113-122</li>
                                   <li>S. V. Dhanal Finite element analysis of band-saw swing frame of band-saw machine International Journal of Current Engineering and Technology, Vol.8,No.5 (Sept/Oct 2018), Page 1250-1253, E-ISSN 2277 - 4106, P-ISSN 2347 - 5161</li>
                                   <li>Mahesh Kadam, "Process Parameter optimization for FDM 3D Printer" International Research Journal of Engineering & Technology (IRJET), V0l.06, Issue04, Page1-6, e-ISSN 2395 - 0056, p-ISSN 2395 - 0072, Impact Factor 7.211, Apr-2019</li>
                                   <li>Mr. Pankaj B. Gavali "A Review On Pesticides Sprayer Technology Approach In Ergonomics, Economics And Ecologic In Agriculture Field "International Journal of Engineering Science Invention (IJESI), Volume 7, Issue 9, Ver-III, ISSN (Online): 2319 - 6734, ISSN (Print): 2319 - 6726,PP 01-05, Sep-18</li>
                                   <li>Mr. A. A. Patwegar, "Design and Fabrication of Material Handling Trolley" International Research Journal of Engineering & Technology (IRJET), V0l.06, Issue03, Page2397-2400, e-ISSN 2395 - 0056, p-ISSN 2395 - 0072</li>
                                   <li>Mrs. Desai P.P., "Use of Casting Simulation for yield Improvement", International Research Journal of Engineering & Technology(IRJET)" V0l.06,Issue03, Page7704-7707, e-ISSN 2395 - 0056, p-ISSN 2395 - 0072, Impact Factor 7.211</li>
                                   <li>Dr. S. G. Bhatwadekar, "OEE (Overall Equipment Effectiveness) Improvement of Qsk-23 Housing Flywheel Line by Implementing Lean Manufacturing", International Research Journal of Engineering & Management (IRJEMS) , V0l.03, Issue04, Page1-10</li>
                                   <li>Dr. S. G. Bhatwadekar, "Reconfigurable Manufacturing System (RMS): A Literature Review", International Journal for Research in Engineering Application & Management (IJREAM), Special Issue-CRTD-2018, Page 35-39 ISSN-2454-9150</li>
                                   <li>Mr. Ajay P. Dhawan "Optimization of Surface Roughness of AISI 304 Austenitic Stainless Steel in Turning Operation Using Taguchi Method" International Journal for Research in Applied Science & Engineering Technology (IJRASET) Vol07, Issue03, Page 1610-1615, ISSN 2321-9563, Impact Factor -6.887</li>
                                   <li>"Reconfigurable Manufacturing System (RMS): A Literature Review", International Journal for Research in Engineering Application & Management (IJREAM), Special Issue-CRTD-2018, Page 35-39, ISSN-2454-9150</li>
                                   <li>Mahesh Kadam, "Design and Development of "Crop Cutter", Journal of Product Design, Quality Engineering and Technology, Volume 3 Issue 3, Page 1-6, Sep-18</li>
                                   <li>Mahesh Kadam, "Design and Development of Weight Operated Material Handling Device Journal of Product Design, Quality Engineering and Technology Volume 1 Issue 2, Page 1-6, Sep-18</li>
                                   <li>Mr. Abhijit A. Patil, "Experimental Studies on friction factor & pressure drop analysis for laminar flow of UCSCJ through a circular vertical pipe fitted with equi-spaced twisted tape", 2nd international conference on Research Advancements in Applied Engineering Science, computer and communication Technologies Institute for engineering research and publication, ISBN No. 978-81-940803-2-9,22nd-23rd March 2019, Thermal Engineering 41-48</li>
                                   <li>Mr. AkshayPotdar,Optimization of Friction Drilling Process by Response Surface Methodology, Published in Springer international journal of Advanced Engineering Optimization Through Intelligent Techniques, Vol.949,pp.351-359, ISBN-978-981-13-8196-6-31, Jul-19</li>
                                   <li>Mr. S. V. Dhanal,Study of the effect of mechanical alloying on the structure of Ni-Mn-Sn Heusler alloy, Published in The Korean Society of Mechanical Engineers and Springer-Verlag GmbH Germany, part of Springer Nature 2020, Journal of Mechanical Science and Technology 34 (1) 2020, Vol34 (1) (2020) 149-154.July-Nov-19</li>
                                   <li>Abhijit A. Patil, Dr. U. C. Kapale,Experimental Study On Augmentation For Laminar Flow Heat Transfer Of Ucscj Through A Circular Vertical Pipe Fitted With Equispaced Tape Inserts published in International Journal of Mechanical and Production Engineering Research and Development (IJMPERD) ISSN(P): 22496890; ISSN(E): 22498001 Vol. 9, Issue 3, Jun 2019, 18211834,SCOPUS Indexed Journal</li>
                                   <li>Dr. S. V. Khandal Augmented Turbulence for Progressive and Efficient Combustion in Biodiesel Diesel Engine published in Arabian Journal for Science and Engineering, ISSN 2193-567X, Jun-19</li>
                                   <li>Dr. S. V. Khandal& Dr. V. A. Raikar An experimental-based artificial neural network performance study of common rail direct injection engine run on plastic pyrolysis oil published in International Journal of Sustainable Engineering indexed in Scopus, Emerging Sources Citation Index (ESCI), and the Web of Science, Taylor & Francishttps://doi.org/10.1080/19397038.2020.1773568,Received 12 Jul 2019, accepted 14 May 2020, Published online: 07 Jun 2020</li>
                                   <li>Mr. P. V. Kulkarni An overview of the formation of fibre waviness and its effect on the mechanical performance of fibre reinforced polymer composites published in Elsevier Journal of Composites Part A: Applied Science and Manufacturing Volume 137, October 2020, 106013, Impact Factor-6.283</li>
                                   <li>Mr. Pratap Vishwas Patwardhan & Dr. Abhijit A. Patil Review of recent advancement in Vapour Absorption Refrigeration System Published in International Journal of Engineering Science Invention (IJESI) ISSN (Online): 2319-6734, ISSN (Print): 2319-6726 www.ijesi.org ||Volume 10 Issue 6 Series III || June 2021 || PP 14-18</li>
                                   <li>Satyajeet U. Manugade1, Sanjaykumar M. Ingale The Effect of Cutting Parameters on the Surface Quality of Different Workpiece Materials for Turning Operation on CNC Machine published in Research and Reviews on Experimental and Applied Mechanics Volume 4 Issue 1, HBRP publication, Page 1-7DOI: http://doi.org/10.5281/zenodo.4896271</li>
                                   <li>Dr. V. V. Kulkarni,MQL Machining with nano fluid: a review published in Manufacturing Rev. 8, 13 (2021), published by EDP Sciences 2021, https://doi.org/10.1051/mfreview/2021011, Received: 14 October 2020 / Accepted: 6 April 2021, Published online 27 April 2021.Vol 8, Article No.13, Number of Pages 18.</li>
                                   <li>Dr. V. V. Kulkarni,Tension-tension fatigue life estimation of CFRP composites by modal testing Published in Materials Today: Proceedings https://doi.org/10.1016/j.matpr.2020.07.436, Volume 46, Part 1, 2021, Pages 217-222</li>
                                   <li>Mr. Nilesh Desai and Mr. Nilesh Sabnis,Analysis of thermo-physical properties of SAE20W40 engine oil by the addition of SiO2 nanoparticles Published in Materials Today: Proceedings https://doi.org/10.1016/j.matpr.2021.03.688, Available online 8 May 2021</li>
                                   <li>Altaf Patvegar,Design and development of coconut crown removal and fibre extraction machine published in International Journal of Advances in Engineering and Management (IJAEM) Volume 3, Issue 6 June 2021, pp: 1237-1243, ISSN: 2395-5252, DOI: 10.35629/5252-030612371243 Impact Factor value 7.429 | ISO 9001: 2008 Certified Journal</li>
                                   <li>S. V. Dhanal, Appasaheb N. Pandav,Analysis of Bandsaw Swing Frame by Vibrometer and FFT published in International Research Journal of Engineering and Technology (IRJET) Volume: 08 Issue: 06 | June 2021, e-ISSN: 2395-0056, p-ISSN: 2395-0072, Impact Factor value: 7.529 | ISO 9001:2008 Certified Journal | Page 557-560</li>
                                   <li>Mr. Omkar Sutar & Dr. U. C. Kapale Experimental Validation of Heat Pipe Solar Collector For Water Heating- a Review published in 2020 Electron Devices Technology and Manufacturing Conference (EDTM) February 24, 2021</li>
                                   <li>Mr. Prathmesh jadhav & Mr. T. B. Shinde Various Nano Catalysts for Biodiesel Production- A Review published in International E-conference on Recent Developments in Engineering & Technology organized by Dhaanish Ahmed Institute of Technology on 3rd April 2021 ICRDET 21</li>
                                   <li>K Balaji, G Wessley, S. V. Khandal, Structural and Thermal Analyses of Gas Turbine Blades with Internal Cooling System Under Steady-State Conditions - Recent Trends in Design, Materials and Manufacturing, 2022, 149-161, Springer</li>
                                   <li>K Balaji, G Wessley, S. V. Khandal, M Gore Enhancement of Aerodynamic Efficiency of a Formula Car by Incorporating a Passive Device in the Front Wing - Recent Trends in Design, Materials and Manufacturing, 2022, 225-237. Springer.</li>
                                   <li>Khandal S. V, Agbulut, Afzal A, Sharifpur M, Abdul Razak K, Khalilpoor N. Influences of hydrogen addition from different dual-fuel modes on engine behaviors. Energy Sci Eng. 2022;00:111. doi:10.1002/ese3.1065</li>
                                   <li>T. M. Yunus Khan, Manzoore Elahi M. Soudagar, S. V. Khandal, Syed Javed, Imran Mokashi, Maughal Ahmed Ali Baig, Khadiga Ahmed Ismail and Ashraf Elfasakhany. Performance of Common Rail Direct Injection (CRDi) Engine Using Ceiba Pentandra Biodiesel and Hydrogen Fuel Combination. Energies 2021, 14, 7142. https://doi.org/10.3390/en14217142</li>
                                   <li>S. V. Khandal, T.M. Yunus Khan, Irfan Anjum Badruddin, Sarfaraz Kamangar, C. Ahamed Saleel, Maughal Ahmed Ali Baig, Salman Ahmed N J. Performance and Emission analysis of Multi-Cylinder Common Rail Direct Injection Diesel Engine Powered with Blends of Tyre Pyrolysis Oil-Ethanol Diesel. 2021, Journal of Engineering Research. DOI: 10.36909/jer.8583</li>
                                   <li>T.M. Yunus Khan, Irfan Anjum Badruddin, Manzoore Elahi M. Soudagar, Sanjeev V. Khandal, Sarfaraz Kamangar, Imran Mokashi, M.A. Mujtaba and Nazia Hossain. Biodiesel Production Using Modified Direct Transesterification by Sequential Use of Acid-Base Catalysis and Performance Evaluation of Diesel Engine Using Various Blends. Sustainability 2021, 13, 9731. https://doi.org/10.3390/su13179731</li>
                                   <li>S. V. Khandal, TM Yunus Khan, Sarfaraz Kamangar, Maughal Ahmed Ali Baig, Salman Ahmed NJ. Effects of hydrogen flow rate, injection pressure and EGR on performance of common rail direct injection (CRDi) engine in dual fuel mode. Frontiers in Engineering and Built Environment, Emerald Publishing Limited, 2021</li>
                                   <li>Pankaj B. Gavali, Sujit S. Patil, Nilesh V. Sabnis, Nilesh S. Desai, H. T Shinde, Modeling and Analysis of Twin Spindle Twin Turret Machine, Journal of Advancement in Machines, Volume-7, Issue-1 (January-April, 2022), pp. 1-13.</li>
                                   <li>Hemant Shinde, Nilesh S. Desai, Nilesh Vijay Sabnis, Pankaj Gavali, Analysing the Impact of using Sio2 and Graphene Oxide Nanoparticles Over the Performance of Vapor Compression Refrigeration System, Journal of Fluid Mechanics and Mechanical Design, Volume-4, Issue- 1 (January-April, 2022).</li>
                                   <li>Nilesh Vijay Sabnis, Nilesh S. Desai, Pankaj Gavali, Hemant Shinde, The Use of SiO2/Deionized Water Nanofluid to Improve the Performance of a Solar Parabolic Trough Collector Fitted with Single Axis Tracking, Journal of Modern Thermodynamics in Mechanical System, Volume-4, Issue-1 (January-April, 2022)</li>
                                   <li>Sanjaykumar Ingale, Pankaj B. Gavali, The Influence of Innovative Teaching Methods on Students Learning, Asian Journal of Science and Applied Technology, Vol.10 No.2 July- December 2021.</li>
                                   <li>Pankaj B Gavali, Appasaheb N. Pandav, Sujit S. Patil, Nilesh V. Sabnis, OEE Improvement of VMC Machine by Implementing Lean Manufacturing for Brake Adapter Ring, International Journal of Contemporary Architecture "The New ARCH" Vol. 8 No. 2 (2021)</li>
                                   <li>Sujit S Patil, Numerical and Experimental Modal Analysis of Go Kart Chassis, International Journal for Research in Applied Science & Engineering Technology (IJRASET), Volume 10 Issue II Feb 2022</li>
                                   <li>Prashant M. Sagare, Analysis and Development of Effective Tool Inventory Management International Journal of Research in Engineering and Science (IJRES) ISSN: 2320-9364 Volume 9, Issue 12, pp: 58-62</li>
                                   <li>Prashant M. Sagare , Adarsh Dilip Desai , Bhushan A. Dongare,Analysis and Development of Effective Tool Inventory Management International Journal of Research in Engineering and Science (IJRES) ISSN (Online): 2320-9364, ISSN (Print): 2320-9356 www.ijres.org Volume 09 Issue 12 ? 2021 ? PP. 58-62</li>
                                   <li>Prajkta P. Desai,Cam Operated, paddle Driven Hammering Machine International Journal of Innovative Research in Technology IJIRT Volume 9 Issue 1 ISSN:2349-6002, 1681-1684, June2022</li>
                                   <li>L. B. Mulla , S. V. Dhanal , T. B. Shinde,Rolling Element Bearing Fault Detection by Vibration Measurement, IOSR Journal of Mechanical and Civil Engineering, ISSN : 2278-1684, Volume No. : 19 Issue No. : 03, Article DOI : 10.9790/1684-1903030108, Date : 27-05-2022</li>
                                   <li>Ajay P. Dhawan , Lalmohammad B. Mulla , Tanaji B. Shinde ,Automatic Braking System using Ultrasonic wave International Journal for Research in Applied Science & Engineering Technology (IJRASET) ISSN: 2321-9653; IC Value: 45.98; SJ Impact Factor: 7.538 Volume 10 Issue VI June 2022</li>
                                   <li>Y. N. Dhulugade,Design & Development of Welding and Checking Fixture for Tractor Hood Assembly International Journal of Scientific Research in Engineering and Management (IJSREM) Volume: 06 Issue: 06 | June - 2022 Impact Factor: 7.185 ISSN: 2582-3930, Pages 1-9</li>
                                   <li>Y. N. Dhulugade,Study of Deep Draw Parameters Using Advanced Techniques Journal of Recent Activities in Production e-ISSN: 2581-9771, Volume-7, Issue-2 (May-August, 2022)</li>
                                   <li>Sanjaykumar Ingale, Pankaj B. Gavali, The Impact of Innovative Methods Based on Students' Learning Styles on Effective Learning, International Conference on Emerging Trends in Engineering and Technology, Nashik, Maharashtra, 07th & 08th, July 2021.</li>
                                   <li>Nilesh S. Desai, The Use of SiO2/Deionized Water Nanofluid to Improve the Performance of a Solar Parabolic Trough Collector Fitted with Single Axis Tracking, ICETEMS-2021.</li>
                                   <li>Hemant T. Shinde, Nilesh S. Desai, Nilesh V. Sabnis, Pankaj B. Gavali,Experimental Investigation on Heat Transfer Enhancement of Nano Fluids in Vapor Compression Refrigeration, ICETET-2021.</li>
                                   <li>Tanaji B. Shinde, Sanjaykumar M. Ingale,The Effect of Hydrogen Enrichment & Variable Compression Ratio on the Emissions of Hydrogen-Diesel Duel Fuel Engine 7th International Conference on Innovation and research in Technology & Engineering(ICIRTE2022) held during 8th & 9th April,2022 at VPPCOE & VA Mumbai</li>
                                   <li>Mulla, L.B., Mujawar, G.G., Gavali, P.B., Dhulugade, Y.N. (2022). Study the Characterization of Hydroxyapatite and Silver Doped Hydroxyapatite Using Pin-on-Disc. In: Dave, H.K., Dixit, U.S., Nedelcu, D. (eds) Recent Advances in Manufacturing Processes and Systems. Lecture Notes in Mechanical Engineering. Springer, Singapore. https://doi.org/10.1007/978-981- 16-7787-8_75</li>
                                   <li>Tanaji Balawant Shinde Production of biodiesel using C3N4-CaO produced from waste eggshell as a catalyst Journal of Emerging Technologies and Innovative Research (JETIR) Volume 9, Issue 8, August 2022, ISSN-2349-5162, Page218-222</li>
                                   <li>Shailendra V, Dhanal, Husainkhan Devadi, V.G. Akkimardi, S.A. Kori (2022) Ni-Mn-Al Heusler Alloy Samples Preparation by Mechanical Alloying Method and Study of their Investigated Properties. Indian Journal of Science and Technology 15(39): 1997-2003. https://doi.org/10.17485/IJST/v15i39.935</li>
                                   <li>S.V.Khandal, Hydrogen and dual fuel mode performing in engine with different combustion chamber shapes: Modelling and analysis using RSM-ANN technique International Journal of Hydrogen Energy, Elsevier, November 2022,</li>
                                </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
   )
}

export default MechanicalDeptNewPublications